http:
  routers:
    web-ui:
      entryPoints:
        - web
      service: web-ui
      rule: PathPrefix(`/`)

  services:
    web-ui:
      loadBalancer:
        servers:
          - url: http://web-ui:8080/
