apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: int-prjcthost-tls
spec:
  secretName: int-prjcthost-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${HOSTNAME}
